CREATE TABLE public.newstudents (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  student_id character varying UNIQUE,
  first_name character varying,
  middle_name character varying,
  last_name character varying,
  dob date,
  gender character varying CHECK (
    gender IS NULL OR (gender::text = ANY (
      ARRAY[
        'M'::character varying, 'F'::character varying, 'O'::character varying,
        'Male'::character varying, 'Female'::character varying, 'Other'::character varying,
        'male'::character varying, 'female'::character varying, 'other'::character varying
      ]::text[]
    ))
  ),
  phone_number character varying,
  email character varying,
  home_address character varying,
  nationality character varying,
  national_id_type character varying,
  national_id_number character varying,
  present_job character varying,
  language_spoken character varying,
  region character varying,
  current_residence character varying,
  hostel_preference character varying,
  any_medical character varying,
  medical_spec character varying,
  disability_spec character varying,
  heard_source character varying,
  heard_spec character varying,
  sponsor_name character varying,
  sponsor_relationship character varying,
  sponsor_occupation character varying,
  sponsor_address character varying,
  sponsor_phone character varying,
  school_name character varying,
  school_location character varying,
  school_year integer,
  school_qualification character varying,
  school_selected character varying,
  program_applying_for character varying,
  program_duration character varying,
  course_type character varying,
  passport_photo_url text,
  wassce_results_url text,
  english_grade character varying,
  mathematics_grade character varying,
  social_studies_grade character varying,
  integrated_science_grade character varying,
  wassce_core_score integer,
  wassce_core_average numeric,
  schools_attended jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  reference_code text,
  status text
);
